<img src='https://kaggle2.blob.core.windows.net/competitions/kaggle/5039/media/kaggle_pets2.png'><br>


From left to right: Shelby, Bailey, Hazel, Daisy, and Yeti.

# Help improve outcomes for shelter animals
https://www.kaggle.com/c/shelter-animal-outcomes

In [1]:
%matplotlib inline
%pylab inline
import pandas as pd
import numpy as np
import seaborn as sns
from __future__ import division

Populating the interactive namespace from numpy and matplotlib

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df_test = pd.read_csv('test.csv')

In [4]:
df

,AnimalID,Name,DateTime,OutcomeType,OutcomeSubtype,AnimalType,SexuponOutcome,AgeuponOutcome,Breed,Color
0,A671945,Hambone,2014-02-12 18:22:00,Return_to_owner,NaN,Dog,Neutered Male,1 year,Shetland Sheepdog Mix,Brown/White
1,A656520,Emily,2013-10-13 12:44:00,Euthanasia,Suffering,Cat,Spayed Female,1 year,Domestic Shorthair Mix,Cream Tabby
2,A686464,Pearce,2015-01-31 12:28:00,Adoption,Foster,Dog,Neutered Male,2 years,Pit Bull Mix,Blue/White
3,A683430,NaN,2014-07-11 19:09:00,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Blue Cream
4,A667013,NaN,2013-11-15 12:52:00,Transfer,Partner,Dog,Neutered Male,2 years,Lhasa Apso/Miniature Poodle,Tan
5,A677334,Elsa,2014-04-25 13:04:00,Transfer,Partner,Dog,Intact Female,1 month,Cairn Terrier/Chihuahua Shorthair,Black/Tan
6,A699218,Jimmy,2015-03-28 13:11:00,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Blue Tabby
7,A701489,NaN,2015-04-30 17:02:00,Transfer,Partner,Cat,Unknown,3 weeks,Domestic Shorthair Mix,Brown Tabby
8,A671784,Lucy,2014-02-04 17:17:00,Adoption,NaN,Dog,Spayed Female,5 months,American Pit Bull Terrier Mix,Red/White
9,A677747,NaN,2014-05-03 07:48:00,Adoption,Offsite,Dog,Spayed Female,1 year,Cairn Terrier,White
10,A668402,NaN,2013-12-05 15:50:00,Transfer,SCRP,Cat,Unknown,2 years,Domestic Shorthair Mix,Black
11,A666320,NaN,2013-11-04 14:48:00,Adoption,NaN,Dog,Spayed Female,2 years,Miniature Schnauzer Mix,Silver
12,A684601,Rocket,2016-02-03 11:27:00,Adoption,Foster,Dog,Neutered Male,4 years,Pit Bull Mix,Brown
13,A704702,Scooter,2015-06-08 16:30:00,Return_to_owner,NaN,Dog,Neutered Male,2 years,Yorkshire Terrier Mix,Black/Red
14,A688584,Preston,2015-11-25 15:00:00,Return_to_owner,NaN,Dog,Neutered Male,1 year,Great Pyrenees Mix,White/Cream
15,A678825,Oliver,2014-07-12 12:10:00,Adoption,Foster,Cat,Neutered Male,3 months,Domestic Shorthair Mix,Orange Tabby/White
16,A678050,NaN,2014-05-03 16:15:00,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Brown Tabby
17,A680028,NaN,2014-06-07 12:54:00,Transfer,Partner,Dog,Intact Female,2 weeks,Pit Bull Mix,Brown/White
18,A679010,Chrissy,2014-05-17 11:32:00,Transfer,Partner,Cat,Intact Female,2 years,Angora Mix,White
19,A684787,Kuma,2014-07-30 17:34:00,Return_to_owner,NaN,Dog,Neutered Male,1 year,Flat Coat Retriever Mix,Black
20,A670658,Anders,2014-01-19 15:03:00,Transfer,Partner,Dog,Intact Male,2 months,Queensland Heeler Mix,Black/White
21,A708812,Munchkin,2015-09-18 15:19:00,Transfer,Partner,Cat,Spayed Female,1 year,Domestic Shorthair Mix,White
22,A705262,Jamaica,2015-08-15 14:22:00,Adoption,NaN,Dog,Spayed Female,2 years,Plott Hound/Boxer,Brown Brindle/White
23,A665781,Quattro,2013-10-28 16:32:00,Adoption,NaN,Dog,Neutered Male,10 months,German Shepherd Mix,Brown/White
24,A676333,Trigger,2014-04-09 17:44:00,Return_to_owner,NaN,Dog,Neutered Male,2 months,German Shepherd Mix,Black/Brown
25,A712750,Olive,2015-10-03 15:44:00,Transfer,Partner,Cat,Intact Female,1 month,Domestic Shorthair Mix,Orange Tabby
26,A718832,Nia,2016-01-15 17:31:00,Adoption,NaN,Dog,Spayed Female,6 months,American Staffordshire Terrier Mix,Chocolate/White
27,A698777,Chloe,2015-03-25 18:50:00,Adoption,NaN,Dog,Spayed Female,5 years,Chihuahua Shorthair Mix,White/Tan
28,A715348,Cymbale,2015-11-21 13:01:00,Adoption,NaN,Cat,Spayed Female,2 months,Domestic Shorthair Mix,Cream Tabby/White
29,A708666,Jax,2015-07-30 14:30:00,Return_to_owner,NaN,Cat,Neutered Male,7 years,Russian Blue Mix,Blue
...,...,...,...,...,...,...,...,...,...,...
26699,A676460,Mario,2014-04-21 14:01:00,Euthanasia,Behavior,Dog,Neutered Male,2 years,American Pit Bull Terrier Mix,White/Black
26700,A704999,Lion,2015-06-15 19:28:00,Return_to_owner,NaN,Dog,Intact Male,10 months,Great Pyrenees/Anatol Shepherd,Tan/Cream
26701,A678842,Ella,2014-06-15 17:41:00,Transfer,Partner,Dog,Intact Female,11 months,Jack Russell Terrier Mix,White/Black
26702,A713637,NaN,2015-10-11 09:42:00,Died,In Kennel,Cat,Spayed Female,2 years,Siamese Mix,Lynx Point
26703,A716670,Mowmow,2015-12-04 12:22:00,Transfer,Partner,Cat,Neutered Male,6 years,Domestic Longhair Mix,Seal Point
26704,A716223,Alice,2015-11-17 17:17:00,Transfer,Partner,Cat,Intact Female,4 weeks,Domestic Shorthair Mix,White/Black
26705,A662498,Grace,2013-10-19 15:34:00,Transfer,Partner,Cat,Intact Female,2 months,Domestic Shorthair Mix,Tortie
26706,A689942,Zoey,2014-10-19 13:29:00,Adoption,NaN,Cat,Spayed Female,2 months,Domestic Shorthair Mix,Black
26707,A682690,NaN,2014-07-01 17:06:00,Euthanasia,Suffering,Cat,Unknown,1 year,Domestic Shorthair Mix,Brown Tabby
26708,A666920,Herbie,2013-11-13 17:32:00,Transfer,Partner,Dog,Neutered Male,2 years,Chihuahua Shorthair Mix,White/Brown
26709,A714386,NaN,2015-10-24 00:00:00,Adoption,NaN,Dog,Spayed Female,1 month,Chihuahua Shorthair Mix,Sable/Buff
26710,A692622,Bonnie,2014-11-24 17:21:00,Transfer,Partner,Dog,Intact Female,1 month,Chihuahua Shorthair/Yorkshire Terrier,Brown/Black
26711,A666284,Sonja,2013-10-30 18:32:00,Transfer,Partner,Dog,Intact Female,1 year,Cocker Spaniel/Dachshund,Buff
26712,A535277,Merlin,2015-04-20 16:04:00,Return_to_owner,NaN,Dog,Neutered Male,12 years,Rat Terrier,Chocolate/Tan
26713,A671169,NaN,2014-01-20 17:37:00,Euthanasia,Suffering,Cat,Intact Female,18 years,Domestic Longhair Mix,Tortie
26714,A679031,Pete,2014-05-31 16:11:00,Adoption,NaN,Cat,Spayed Female,2 months,Domestic Shorthair Mix,Orange Tabby
26715,A708833,Luna,2015-08-05 17:03:00,Adoption,NaN,Dog,Spayed Female,2 months,Pointer Mix,Black/White
26716,A697158,Max,2015-05-02 21:04:00,Adoption,Offsite,Dog,Neutered Male,2 months,Newfoundland Mix,White/Black
26717,A519949,Bella,2014-06-30 17:34:00,Return_to_owner,NaN,Dog,Spayed Female,9 years,Bullmastiff Mix,Black
26718,A701044,NaN,2015-04-28 14:26:00,Adoption,NaN,Dog,Neutered Male,2 months,Siberian Husky/German Shepherd,Black/Tricolor
26719,A707871,NaN,2015-07-20 09:00:00,Transfer,SCRP,Cat,Unknown,2 years,Domestic Shorthair Mix,Brown Tabby/White
26720,A704405,Brownie,2015-07-18 14:08:00,Adoption,NaN,Cat,Spayed Female,2 months,Domestic Shorthair Mix,Brown Tabby
26721,A662019,Green Bean,2014-07-17 09:43:00,Adoption,Foster,Cat,Spayed Female,5 years,Domestic Shorthair Mix,Black
26722,A687056,NaN,2014-08-31 09:00:00,Transfer,SCRP,Cat,Intact Male,5 months,Domestic Shorthair Mix,Orange Tabby
26723,A716997,Zeus,2016-01-29 18:52:00,Adoption,NaN,Dog,Neutered Male,6 years,Staffordshire Mix,Blue/White
26724,A702446,NaN,2015-05-14 11:56:00,Transfer,Partner,Cat,Intact Male,1 month,Domestic Shorthair Mix,Brown Tabby/White
26725,A718934,NaN,2016-01-20 18:59:00,Transfer,SCRP,Cat,Spayed Female,3 months,Domestic Shorthair Mix,Brown Tabby
26726,A698128,Zeus,2015-03-09 13:33:00,Adoption,NaN,Dog,Neutered Male,4 years,Old English Bulldog Mix,White/Tan
26727,A677478,NaN,2014-04-27 12:22:00,Transfer,Partner,Cat,Intact Male,4 weeks,Domestic Shorthair Mix,Black
26728,A706629,NaN,2015-07-02 09:00:00,Transfer,SCRP,Cat,Intact Male,1 year,Domestic Shorthair Mix,Brown Tabby/White

Про породы: https://www.kaggle.com/msjgriffiths/shelter-animal-outcomes/breed-n-grams-visualization

In [5]:
df['OutcomeType'].value_counts(dropna=False, normalize=True)

Adoption           0.402896
Transfer           0.352501
Return_to_owner    0.179056
Euthanasia         0.058177
Died               0.007370
Name: OutcomeType, dtype: float64

In [6]:
df['SexuponOutcome'].value_counts(dropna=False)

Neutered Male    9779
Spayed Female    8820
Intact Male      3525
Intact Female    3511
Unknown          1093
NaN                 1
Name: SexuponOutcome, dtype: int64

In [7]:
df['SexuponOutcome'] = df['SexuponOutcome'].fillna('Unknown')
df_test['SexuponOutcome'] = df_test['SexuponOutcome'].fillna('Unknown')

In [8]:
df['SexuponOutcome'].value_counts(dropna=False)

Neutered Male    9779
Spayed Female    8820
Intact Male      3525
Intact Female    3511
Unknown          1094
Name: SexuponOutcome, dtype: int64

In [9]:
df['SexuponOutcome'] = df['SexuponOutcome'].astype('str')
df_test['SexuponOutcome'] = df_test['SexuponOutcome'].astype('str')

In [10]:
def detect_sterilization(x):
    if 'Intact' in x:
        return 'Intact'
    if 'Spayed' in x or 'Neutered' in x:
        return 'Neutered'
    return 'Unknown'
def detect_gender(x):
    if 'Male' in x:
        return 'Male'
    if 'Female' in x:
        return 'Female'
    return 'Unknown'
df['Sterilization'] = df['SexuponOutcome'].map(detect_sterilization)
df['Gender'] = df['SexuponOutcome'].map(detect_sterilization)

df_test['Sterilization'] = df['SexuponOutcome'].map(detect_sterilization)
df_test['Gender'] = df['SexuponOutcome'].map(detect_sterilization)

In [11]:
df['Sterilization'].value_counts()

Neutered    18599
Intact       7036
Unknown      1094
Name: Sterilization, dtype: int64

In [12]:
df['Sterilization']

0        Neutered
1        Neutered
2        Neutered
3          Intact
4        Neutered
5          Intact
6          Intact
7         Unknown
8        Neutered
9        Neutered
10        Unknown
11       Neutered
12       Neutered
13       Neutered
14       Neutered
15       Neutered
16         Intact
17         Intact
18         Intact
19       Neutered
20         Intact
21       Neutered
22       Neutered
23       Neutered
24       Neutered
25         Intact
26       Neutered
27       Neutered
28       Neutered
29       Neutered
           ...
26699    Neutered
26700      Intact
26701      Intact
26702    Neutered
26703    Neutered
26704      Intact
26705      Intact
26706    Neutered
26707     Unknown
26708    Neutered
26709    Neutered
26710      Intact
26711      Intact
26712    Neutered
26713      Intact
26714    Neutered
26715    Neutered
26716    Neutered
26717    Neutered
26718    Neutered
26719     Unknown
26720    Neutered
26721    Neutered
26722      Intact
26723    Neutered
26724      Intact
26725    Neutered
26726    Neutered
26727      Intact
26728      Intact
Name: Sterilization, dtype: object

In [13]:
df['Gender'].value_counts()

Neutered    18599
Intact       7036
Unknown      1094
Name: Gender, dtype: int64

In [14]:
sterilization = pd.get_dummies(df['Sterilization'], prefix='Sterilization', drop_first=True)
df = pd.concat([df, sterilization], axis=1)
gender = pd.get_dummies(df['Gender'], prefix='Gender', drop_first=True)
df = pd.concat([df, gender], axis=1)

sterilization = pd.get_dummies(df_test['Sterilization'], prefix='Sterilization', drop_first=True)
df_test = pd.concat([df_test, sterilization], axis=1)
gender = pd.get_dummies(df_test['Gender'], prefix='Gender', drop_first=True)
df_test = pd.concat([df_test, gender], axis=1)

См. еще <a href='http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html'>OneHotEncoder</a>

И еще: https://github.com/pandas-dev/pandas/issues/8918

In [15]:
df

,AnimalID,Name,DateTime,OutcomeType,OutcomeSubtype,AnimalType,SexuponOutcome,AgeuponOutcome,Breed,Color,Sterilization,Gender,Sterilization_Neutered,Sterilization_Unknown,Gender_Neutered,Gender_Unknown
0,A671945,Hambone,2014-02-12 18:22:00,Return_to_owner,NaN,Dog,Neutered Male,1 year,Shetland Sheepdog Mix,Brown/White,Neutered,Neutered,1,0,1,0
1,A656520,Emily,2013-10-13 12:44:00,Euthanasia,Suffering,Cat,Spayed Female,1 year,Domestic Shorthair Mix,Cream Tabby,Neutered,Neutered,1,0,1,0
2,A686464,Pearce,2015-01-31 12:28:00,Adoption,Foster,Dog,Neutered Male,2 years,Pit Bull Mix,Blue/White,Neutered,Neutered,1,0,1,0
3,A683430,NaN,2014-07-11 19:09:00,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Blue Cream,Intact,Intact,0,0,0,0
4,A667013,NaN,2013-11-15 12:52:00,Transfer,Partner,Dog,Neutered Male,2 years,Lhasa Apso/Miniature Poodle,Tan,Neutered,Neutered,1,0,1,0
5,A677334,Elsa,2014-04-25 13:04:00,Transfer,Partner,Dog,Intact Female,1 month,Cairn Terrier/Chihuahua Shorthair,Black/Tan,Intact,Intact,0,0,0,0
6,A699218,Jimmy,2015-03-28 13:11:00,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Blue Tabby,Intact,Intact,0,0,0,0
7,A701489,NaN,2015-04-30 17:02:00,Transfer,Partner,Cat,Unknown,3 weeks,Domestic Shorthair Mix,Brown Tabby,Unknown,Unknown,0,1,0,1
8,A671784,Lucy,2014-02-04 17:17:00,Adoption,NaN,Dog,Spayed Female,5 months,American Pit Bull Terrier Mix,Red/White,Neutered,Neutered,1,0,1,0
9,A677747,NaN,2014-05-03 07:48:00,Adoption,Offsite,Dog,Spayed Female,1 year,Cairn Terrier,White,Neutered,Neutered,1,0,1,0
10,A668402,NaN,2013-12-05 15:50:00,Transfer,SCRP,Cat,Unknown,2 years,Domestic Shorthair Mix,Black,Unknown,Unknown,0,1,0,1
11,A666320,NaN,2013-11-04 14:48:00,Adoption,NaN,Dog,Spayed Female,2 years,Miniature Schnauzer Mix,Silver,Neutered,Neutered,1,0,1,0
12,A684601,Rocket,2016-02-03 11:27:00,Adoption,Foster,Dog,Neutered Male,4 years,Pit Bull Mix,Brown,Neutered,Neutered,1,0,1,0
13,A704702,Scooter,2015-06-08 16:30:00,Return_to_owner,NaN,Dog,Neutered Male,2 years,Yorkshire Terrier Mix,Black/Red,Neutered,Neutered,1,0,1,0
14,A688584,Preston,2015-11-25 15:00:00,Return_to_owner,NaN,Dog,Neutered Male,1 year,Great Pyrenees Mix,White/Cream,Neutered,Neutered,1,0,1,0
15,A678825,Oliver,2014-07-12 12:10:00,Adoption,Foster,Cat,Neutered Male,3 months,Domestic Shorthair Mix,Orange Tabby/White,Neutered,Neutered,1,0,1,0
16,A678050,NaN,2014-05-03 16:15:00,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Brown Tabby,Intact,Intact,0,0,0,0
17,A680028,NaN,2014-06-07 12:54:00,Transfer,Partner,Dog,Intact Female,2 weeks,Pit Bull Mix,Brown/White,Intact,Intact,0,0,0,0
18,A679010,Chrissy,2014-05-17 11:32:00,Transfer,Partner,Cat,Intact Female,2 years,Angora Mix,White,Intact,Intact,0,0,0,0
19,A684787,Kuma,2014-07-30 17:34:00,Return_to_owner,NaN,Dog,Neutered Male,1 year,Flat Coat Retriever Mix,Black,Neutered,Neutered,1,0,1,0
20,A670658,Anders,2014-01-19 15:03:00,Transfer,Partner,Dog,Intact Male,2 months,Queensland Heeler Mix,Black/White,Intact,Intact,0,0,0,0
21,A708812,Munchkin,2015-09-18 15:19:00,Transfer,Partner,Cat,Spayed Female,1 year,Domestic Shorthair Mix,White,Neutered,Neutered,1,0,1,0
22,A705262,Jamaica,2015-08-15 14:22:00,Adoption,NaN,Dog,Spayed Female,2 years,Plott Hound/Boxer,Brown Brindle/White,Neutered,Neutered,1,0,1,0
23,A665781,Quattro,2013-10-28 16:32:00,Adoption,NaN,Dog,Neutered Male,10 months,German Shepherd Mix,Brown/White,Neutered,Neutered,1,0,1,0
24,A676333,Trigger,2014-04-09 17:44:00,Return_to_owner,NaN,Dog,Neutered Male,2 months,German Shepherd Mix,Black/Brown,Neutered,Neutered,1,0,1,0
25,A712750,Olive,2015-10-03 15:44:00,Transfer,Partner,Cat,Intact Female,1 month,Domestic Shorthair Mix,Orange Tabby,Intact,Intact,0,0,0,0
26,A718832,Nia,2016-01-15 17:31:00,Adoption,NaN,Dog,Spayed Female,6 months,American Staffordshire Terrier Mix,Chocolate/White,Neutered,Neutered,1,0,1,0
27,A698777,Chloe,2015-03-25 18:50:00,Adoption,NaN,Dog,Spayed Female,5 years,Chihuahua Shorthair Mix,White/Tan,Neutered,Neutered,1,0,1,0
28,A715348,Cymbale,2015-11-21 13:01:00,Adoption,NaN,Cat,Spayed Female,2 months,Domestic Shorthair Mix,Cream Tabby/White,Neutered,Neutered,1,0,1,0
29,A708666,Jax,2015-07-30 14:30:00,Return_to_owner,NaN,Cat,Neutered Male,7 years,Russian Blue Mix,Blue,Neutered,Neutered,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26699,A676460,Mario,2014-04-21 14:01:00,Euthanasia,Behavior,Dog,Neutered Male,2 years,American Pit Bull Terrier Mix,White/Black,Neutered,Neutered,1,0,1,0
26700,A704999,Lion,2015-06-15 19:28:00,Return_to_owner,NaN,Dog,Intact Male,10 months,Great Pyrenees/Anatol Shepherd,Tan/Cream,Intact,Intact,0,0,0,0
26701,A678842,Ella,2014-06-15 17:41:00,Transfer,Partner,Dog,Intact Female,11 months,Jack Russell Terrier Mix,White/Black,Intact,Intact,0,0,0,0
26702,A713637,NaN,2015-10-11 09:42:00,Died,In Kennel,Cat,Spayed Female,2 years,Siamese Mix,Lynx Point,Neutered,Neutered,1,0,1,0
26703,A716670,Mowmow,2015-12-04 12:22:00,Transfer,Partner,Cat,Neutered Male,6 years,Domestic Longhair Mix,Seal Point,Neutered,Neutered,1,0,1,0
26704,A716223,Alice,2015-11-17 17:17:00,Transfer,Partner,Cat,Intact Female,4 weeks,Domestic Shorthair Mix,White/Black,Intact,Intact,0,0,0,0
26705,A662498,Grace,2013-10-19 15:34:00,Transfer,Partner,Cat,Intact Female,2 months,Domestic Shorthair Mix,Tortie,Intact,Intact,0,0,0,0
26706,A689942,Zoey,2014-10-19 13:29:00,Adoption,NaN,Cat,Spayed Female,2 months,Domestic Shorthair Mix,Black,Neutered,Neutered,1,0,1,0
26707,A682690,NaN,2014-07-01 17:06:00,Euthanasia,Suffering,Cat,Unknown,1 year,Domestic Shorthair Mix,Brown Tabby,Unknown,Unknown,0,1,0,1
26708,A666920,Herbie,2013-11-13 17:32:00,Transfer,Partner,Dog,Neutered Male,2 years,Chihuahua Shorthair Mix,White/Brown,Neutered,Neutered,1,0,1,0
26709,A714386,NaN,2015-10-24 00:00:00,Adoption,NaN,Dog,Spayed Female,1 month,Chihuahua Shorthair Mix,Sable/Buff,Neutered,Neutered,1,0,1,0
26710,A692622,Bonnie,2014-11-24 17:21:00,Transfer,Partner,Dog,Intact Female,1 month,Chihuahua Shorthair/Yorkshire Terrier,Brown/Black,Intact,Intact,0,0,0,0
26711,A666284,Sonja,2013-10-30 18:32:00,Transfer,Partner,Dog,Intact Female,1 year,Cocker Spaniel/Dachshund,Buff,Intact,Intact,0,0,0,0
26712,A535277,Merlin,2015-04-20 16:04:00,Return_to_owner,NaN,Dog,Neutered Male,12 years,Rat Terrier,Chocolate/Tan,Neutered,Neutered,1,0,1,0
26713,A671169,NaN,2014-01-20 17:37:00,Euthanasia,Suffering,Cat,Intact Female,18 years,Domestic Longhair Mix,Tortie,Intact,Intact,0,0,0,0
26714,A679031,Pete,2014-05-31 16:11:00,Adoption,NaN,Cat,Spayed Female,2 months,Domestic Shorthair Mix,Orange Tabby,Neutered,Neutered,1,0,1,0
26715,A708833,Luna,2015-08-05 17:03:00,Adoption,NaN,Dog,Spayed Female,2 months,Pointer Mix,Black/White,Neutered,Neutered,1,0,1,0
26716,A697158,Max,2015-05-02 21:04:00,Adoption,Offsite,Dog,Neutered Male,2 months,Newfoundland Mix,White/Black,Neutered,Neutered,1,0,1,0
26717,A519949,Bella,2014-06-30 17:34:00,Return_to_owner,NaN,Dog,Spayed Female,9 years,Bullmastiff Mix,Black,Neutered,Neutered,1,0,1,0
26718,A701044,NaN,2015-04-28 14:26:00,Adoption,NaN,Dog,Neutered Male,2 months,Siberian Husky/German Shepherd,Black/Tricolor,Neutered,Neutered,1,0,1,0
26719,A707871,NaN,2015-07-20 09:00:00,Transfer,SCRP,Cat,Unknown,2 years,Domestic Shorthair Mix,Brown Tabby/White,Unknown,Unknown,0,1,0,1
26720,A704405,Brownie,2015-07-18 14:08:00,Adoption,NaN,Cat,Spayed Female,2 months,Domestic Shorthair Mix,Brown Tabby,Neutered,Neutered,1,0,1,0
26721,A662019,Green Bean,2014-07-17 09:43:00,Adoption,Foster,Cat,Spayed Female,5 years,Domestic Shorthair Mix,Black,Neutered,Neutered,1,0,1,0
26722,A687056,NaN,2014-08-31 09:00:00,Transfer,SCRP,Cat,Intact Male,5 months,Domestic Shorthair Mix,Orange Tabby,Intact,Intact,0,0,0,0
26723,A716997,Zeus,2016-01-29 18:52:00,Adoption,NaN,Dog,Neutered Male,6 years,Staffordshire Mix,Blue/White,Neutered,Neutered,1,0,1,0
26724,A702446,NaN,2015-05-14 11:56:00,Transfer,Partner,Cat,Intact Male,1 month,Domestic Shorthair Mix,Brown Tabby/White,Intact,Intact,0,0,0,0
26725,A718934,NaN,2016-01-20 18:59:00,Transfer,SCRP,Cat,Spayed Female,3 months,Domestic Shorthair Mix,Brown Tabby,Neutered,Neutered,1,0,1,0
26726,A698128,Zeus,2015-03-09 13:33:00,Adoption,NaN,Dog,Neutered Male,4 years,Old English Bulldog Mix,White/Tan,Neutered,Neutered,1,0,1,0
26727,A677478,NaN,2014-04-27 12:22:00,Transfer,Partner,Cat,Intact Male,4 weeks,Domestic Shorthair Mix,Black,Intact,Intact,0,0,0,0
26728,A706629,NaN,2015-07-02 09:00:00,Transfer,SCRP,Cat,Intact Male,1 year,Domestic Shorthair Mix,Brown Tabby/White,Intact,Intact,0,0,0,0

In [16]:
del df['Sterilization_Unknown']
del df_test['Sterilization_Unknown']

In [17]:
df['AnimalType'].value_counts(dropna=False)
df_test['AnimalType'].value_counts(dropna=False)

Dog    6656
Cat    4800
Name: AnimalType, dtype: int64

In [18]:
df['AnimalType'] = df['AnimalType'].map({'Dog': 0, 'Cat': 1})
df_test['AnimalType'] = df_test['AnimalType'].map({'Dog': 0, 'Cat': 1})

In [19]:
df['AgeuponOutcome'].value_counts(dropna=False)

1 year       3969
2 years      3742
2 months     3397
3 years      1823
1 month      1281
3 months     1277
4 years      1071
5 years       992
4 months      888
6 years       670
3 weeks       659
5 months      652
6 months      588
8 years       536
7 years       531
2 weeks       529
10 months     457
10 years      446
8 months      402
4 weeks       334
7 months      288
9 years       288
12 years      234
9 months      224
1 weeks       171
11 months     166
1 week        146
13 years      143
11 years      126
3 days        109
2 days         99
14 years       97
15 years       85
1 day          66
6 days         50
4 days         50
16 years       36
5 days         24
0 years        22
NaN            18
17 years       17
5 weeks        11
18 years       10
19 years        3
20 years        2
Name: AgeuponOutcome, dtype: int64

In [20]:
df['AgeuponOutcome'] = df['AgeuponOutcome'].fillna('unknown')
df_test['AgeuponOutcome'] = df_test['AgeuponOutcome'].fillna('unknown')

In [21]:
def get_age_in_weeks(age_str):
    if age_str == 'unknown':
        return -50
    number, time_period = age_str.split()
    multiplicator = 1
    if time_period == 'years':
        multiplicator = 365 / 7
    elif time_period == 'months':
        multiplicator = 30 / 7
    return int(number) * multiplicator

df['AgeuponOutcome'] = df['AgeuponOutcome'].map(get_age_in_weeks)
df_test['AgeuponOutcome'] = df_test['AgeuponOutcome'].map(get_age_in_weeks)

In [22]:
df['Color'].value_counts(dropna=False)

Black/White                  2824
Black                        2292
Brown Tabby                  1635
Brown Tabby/White             940
White                         931
Brown/White                   884
Orange Tabby                  841
Tan/White                     773
Tricolor                      752
Blue/White                    702
Black/Tan                     672
White/Black                   643
Brown                         639
Tan                           628
White/Brown                   569
Tortie                        530
Calico                        517
Orange Tabby/White            455
Brown Brindle/White           450
Blue                          450
Black/Brown                   436
Blue Tabby                    433
White/Tan                     389
Red                           337
Torbie                        335
Brown/Black                   333
Red/White                     331
Blue Tabby/White              241
Brown Brindle                 232
Chocolate/White               224
                             ...
Red/Gold                        1
Lynx Point/Brown Tabby          1
Liver Tick/White                1
Brown Tabby/Brown               1
Blue/Brown                      1
Tan/Brown Brindle               1
Tortie/Black Smoke              1
Brown/Blue                      1
White/Black Smoke               1
Tricolor/Brown Merle            1
Tan/Brown Merle                 1
Tricolor/Blue Merle             1
Brown Merle/Tan                 1
Sable/Red                       1
Tan/Tricolor                    1
Brown Brindle/Brown Merle       1
Chocolate/Red Tick              1
Blue Merle/Red                  1
Brown/Black Brindle             1
Blue Cream/Tortie               1
Tan/Yellow Brindle              1
Silver/Red                      1
Red Tick/Brown Merle            1
Fawn/Brown                      1
Calico/Blue Tabby               1
Blue Merle/Cream                1
Blue Tabby/Tan                  1
Brown Brindle/Blue Cream        1
Blue Cream/Buff                 1
Blue Cream/Blue Tabby           1
Name: Color, dtype: int64

In [23]:
df['Color'].value_counts(dropna=False)[:100].axes

[Index([u'Black/White', u'Black', u'Brown Tabby', u'Brown Tabby/White',
        u'White', u'Brown/White', u'Orange Tabby', u'Tan/White', u'Tricolor',
        u'Blue/White', u'Black/Tan', u'White/Black', u'Brown', u'Tan',
        u'White/Brown', u'Tortie', u'Calico', u'Orange Tabby/White',
        u'Brown Brindle/White', u'Blue', u'Black/Brown', u'Blue Tabby',
        u'White/Tan', u'Red', u'Torbie', u'Brown/Black', u'Red/White',
        u'Blue Tabby/White', u'Brown Brindle', u'Chocolate/White', u'Buff',
        u'Sable', u'Cream Tabby', u'Yellow', u'Tan/Black', u'Lynx Point',
        u'Cream', u'Chocolate', u'Seal Point', u'White/Blue',
        u'White/Brown Brindle', u'Fawn/White', u'White/Brown Tabby',
        u'Gray/White', u'Gray', u'Sable/White', u'Flame Point',
        u'Cream Tabby/White', u'Blue Merle', u'Black Brindle/White', u'Fawn',
        u'Chocolate/Tan', u'Red/Black', u'Torbie/White', u'White/Gray',
        u'White/Red', u'Gold', u'White/Orange Tabby', u'Brown/Tan',
        u'White/Tricolor', u'Black Smoke', u'Black/Brown Brindle',
        u'Blue Merle/White', u'Yellow/White', u'Buff/White', u'Black Tabby',
        u'Lilac Point', u'Black/Tricolor', u'White/Chocolate', u'White/Buff',
        u'Cream/White', u'Black/Gray', u'White/Cream', u'Brown Merle',
        u'Gray Tabby', u'Blue/Tan', u'Brown Merle/White', u'Tortie/White',
        u'Tortie Point', u'White/Orange', u'Blue Point', u'Silver Tabby',
        u'Blue Merle/Tan', u'Red Merle', u'Orange/White', u'Red/Tan',
        u'Calico Point', u'Tan/Brown', u'Calico/White', u'Red Merle/White',
        u'Apricot', u'Black Brindle', u'Silver/Tan', u'Fawn/Black',
        u'Seal Point/White', u'Gold/White', u'Tricolor/White',
        u'Black Tabby/White', u'Blue Tick', u'Silver'],
       dtype='object')]

In [24]:
popular_colors = set(df['Color'].value_counts(dropna=False)[:100].axes[0])

In [25]:
df['Color'] = df['Color'].map(lambda x: 'Rare' if x not in popular_colors else x)
df_test['Color'] = df_test['Color'].map(lambda x: 'Rare' if x not in popular_colors else x)

In [26]:
df['Color'].value_counts()

Black/White            2824
Black                  2292
Brown Tabby            1635
Brown Tabby/White       940
White                   931
Rare                    927
Brown/White             884
Orange Tabby            841
Tan/White               773
Tricolor                752
Blue/White              702
Black/Tan               672
White/Black             643
Brown                   639
Tan                     628
White/Brown             569
Tortie                  530
Calico                  517
Orange Tabby/White      455
Brown Brindle/White     450
Blue                    450
Black/Brown             436
Blue Tabby              433
White/Tan               389
Red                     337
Torbie                  335
Brown/Black             333
Red/White               331
Blue Tabby/White        241
Brown Brindle           232
                       ...
Black/Gray               38
Cream/White              38
White/Cream              36
Gray Tabby               35
Brown Merle              35
Brown Merle/White        33
Blue/Tan                 33
Tortie/White             33
Tortie Point             32
White/Orange             30
Blue Point               29
Silver Tabby             28
Red Merle                26
Orange/White             26
Blue Merle/Tan           26
Red/Tan                  26
Calico Point             25
Calico/White             24
Tan/Brown                24
Red Merle/White          23
Apricot                  21
Silver/Tan               20
Black Brindle            20
Seal Point/White         19
Fawn/Black               19
Gold/White               19
Blue Tick                18
Tricolor/White           18
Black Tabby/White        18
Silver                   17
Name: Color, dtype: int64

In [27]:
color = pd.get_dummies(df['Color'], prefix='Color', drop_first=True)
df = pd.concat([df, color], axis=1)

color = pd.get_dummies(df_test['Color'], prefix='Color', drop_first=True)
df_test = pd.concat([df_test, color], axis=1)

In [28]:
df

,AnimalID,Name,DateTime,OutcomeType,OutcomeSubtype,AnimalType,SexuponOutcome,AgeuponOutcome,Breed,Color,...,Color_White/Chocolate,Color_White/Cream,Color_White/Gray,Color_White/Orange,Color_White/Orange Tabby,Color_White/Red,Color_White/Tan,Color_White/Tricolor,Color_Yellow,Color_Yellow/White
0,A671945,Hambone,2014-02-12 18:22:00,Return_to_owner,NaN,0,Neutered Male,1.000000,Shetland Sheepdog Mix,Brown/White,...,0,0,0,0,0,0,0,0,0,0
1,A656520,Emily,2013-10-13 12:44:00,Euthanasia,Suffering,1,Spayed Female,1.000000,Domestic Shorthair Mix,Cream Tabby,...,0,0,0,0,0,0,0,0,0,0
2,A686464,Pearce,2015-01-31 12:28:00,Adoption,Foster,0,Neutered Male,104.285714,Pit Bull Mix,Blue/White,...,0,0,0,0,0,0,0,0,0,0
3,A683430,NaN,2014-07-11 19:09:00,Transfer,Partner,1,Intact Male,3.000000,Domestic Shorthair Mix,Rare,...,0,0,0,0,0,0,0,0,0,0
4,A667013,NaN,2013-11-15 12:52:00,Transfer,Partner,0,Neutered Male,104.285714,Lhasa Apso/Miniature Poodle,Tan,...,0,0,0,0,0,0,0,0,0,0
5,A677334,Elsa,2014-04-25 13:04:00,Transfer,Partner,0,Intact Female,1.000000,Cairn Terrier/Chihuahua Shorthair,Black/Tan,...,0,0,0,0,0,0,0,0,0,0
6,A699218,Jimmy,2015-03-28 13:11:00,Transfer,Partner,1,Intact Male,3.000000,Domestic Shorthair Mix,Blue Tabby,...,0,0,0,0,0,0,0,0,0,0
7,A701489,NaN,2015-04-30 17:02:00,Transfer,Partner,1,Unknown,3.000000,Domestic Shorthair Mix,Brown Tabby,...,0,0,0,0,0,0,0,0,0,0
8,A671784,Lucy,2014-02-04 17:17:00,Adoption,NaN,0,Spayed Female,21.428571,American Pit Bull Terrier Mix,Red/White,...,0,0,0,0,0,0,0,0,0,0
9,A677747,NaN,2014-05-03 07:48:00,Adoption,Offsite,0,Spayed Female,1.000000,Cairn Terrier,White,...,0,0,0,0,0,0,0,0,0,0
10,A668402,NaN,2013-12-05 15:50:00,Transfer,SCRP,1,Unknown,104.285714,Domestic Shorthair Mix,Black,...,0,0,0,0,0,0,0,0,0,0
11,A666320,NaN,2013-11-04 14:48:00,Adoption,NaN,0,Spayed Female,104.285714,Miniature Schnauzer Mix,Silver,...,0,0,0,0,0,0,0,0,0,0
12,A684601,Rocket,2016-02-03 11:27:00,Adoption,Foster,0,Neutered Male,208.571429,Pit Bull Mix,Brown,...,0,0,0,0,0,0,0,0,0,0
13,A704702,Scooter,2015-06-08 16:30:00,Return_to_owner,NaN,0,Neutered Male,104.285714,Yorkshire Terrier Mix,Rare,...,0,0,0,0,0,0,0,0,0,0
14,A688584,Preston,2015-11-25 15:00:00,Return_to_owner,NaN,0,Neutered Male,1.000000,Great Pyrenees Mix,White/Cream,...,0,1,0,0,0,0,0,0,0,0
15,A678825,Oliver,2014-07-12 12:10:00,Adoption,Foster,1,Neutered Male,12.857143,Domestic Shorthair Mix,Orange Tabby/White,...,0,0,0,0,0,0,0,0,0,0
16,A678050,NaN,2014-05-03 16:15:00,Transfer,Partner,1,Intact Male,3.000000,Domestic Shorthair Mix,Brown Tabby,...,0,0,0,0,0,0,0,0,0,0
17,A680028,NaN,2014-06-07 12:54:00,Transfer,Partner,0,Intact Female,2.000000,Pit Bull Mix,Brown/White,...,0,0,0,0,0,0,0,0,0,0
18,A679010,Chrissy,2014-05-17 11:32:00,Transfer,Partner,1,Intact Female,104.285714,Angora Mix,White,...,0,0,0,0,0,0,0,0,0,0
19,A684787,Kuma,2014-07-30 17:34:00,Return_to_owner,NaN,0,Neutered Male,1.000000,Flat Coat Retriever Mix,Black,...,0,0,0,0,0,0,0,0,0,0
20,A670658,Anders,2014-01-19 15:03:00,Transfer,Partner,0,Intact Male,8.571429,Queensland Heeler Mix,Black/White,...,0,0,0,0,0,0,0,0,0,0
21,A708812,Munchkin,2015-09-18 15:19:00,Transfer,Partner,1,Spayed Female,1.000000,Domestic Shorthair Mix,White,...,0,0,0,0,0,0,0,0,0,0
22,A705262,Jamaica,2015-08-15 14:22:00,Adoption,NaN,0,Spayed Female,104.285714,Plott Hound/Boxer,Brown Brindle/White,...,0,0,0,0,0,0,0,0,0,0
23,A665781,Quattro,2013-10-28 16:32:00,Adoption,NaN,0,Neutered Male,42.857143,German Shepherd Mix,Brown/White,...,0,0,0,0,0,0,0,0,0,0
24,A676333,Trigger,2014-04-09 17:44:00,Return_to_owner,NaN,0,Neutered Male,8.571429,German Shepherd Mix,Black/Brown,...,0,0,0,0,0,0,0,0,0,0
25,A712750,Olive,2015-10-03 15:44:00,Transfer,Partner,1,Intact Female,1.000000,Domestic Shorthair Mix,Orange Tabby,...,0,0,0,0,0,0,0,0,0,0
26,A718832,Nia,2016-01-15 17:31:00,Adoption,NaN,0,Spayed Female,25.714286,American Staffordshire Terrier Mix,Chocolate/White,...,0,0,0,0,0,0,0,0,0,0
27,A698777,Chloe,2015-03-25 18:50:00,Adoption,NaN,0,Spayed Female,260.714286,Chihuahua Shorthair Mix,White/Tan,...,0,0,0,0,0,0,1,0,0,0
28,A715348,Cymbale,2015-11-21 13:01:00,Adoption,NaN,1,Spayed Female,8.571429,Domestic Shorthair Mix,Cream Tabby/White,...,0,0,0,0,0,0,0,0,0,0
29,A708666,Jax,2015-07-30 14:30:00,Return_to_owner,NaN,1,Neutered Male,365.000000,Russian Blue Mix,Blue,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26699,A676460,Mario,2014-04-21 14:01:00,Euthanasia,Behavior,0,Neutered Male,104.285714,American Pit Bull Terrier Mix,White/Black,...,0,0,0,0,0,0,0,0,0,0
26700,A704999,Lion,2015-06-15 19:28:00,Return_to_owner,NaN,0,Intact Male,42.857143,Great Pyrenees/Anatol Shepherd,Rare,...,0,0,0,0,0,0,0,0,0,0
26701,A678842,Ella,2014-06-15 17:41:00,Transfer,Partner,0,Intact Female,47.142857,Jack Russell Terrier Mix,White/Black,...,0,0,0,0,0,0,0,0,0,0
26702,A713637,NaN,2015-10-11 09:42:00,Died,In Kennel,1,Spayed Female,104.285714,Siamese Mix,Lynx Point,...,0,0,0,0,0,0,0,0,0,0
26703,A716670,Mowmow,2015-12-04 12:22:00,Transfer,Partner,1,Neutered Male,312.857143,Domestic Longhair Mix,Seal Point,...,0,0,0,0,0,0,0,0,0,0
26704,A716223,Alice,2015-11-17 17:17:00,Transfer,Partner,1,Intact Female,4.000000,Domestic Shorthair Mix,White/Black,...,0,0,0,0,0,0,0,0,0,0
26705,A662498,Grace,2013-10-19 15:34:00,Transfer,Partner,1,Intact Female,8.571429,Domestic Shorthair Mix,Tortie,...,0,0,0,0,0,0,0,0,0,0
26706,A689942,Zoey,2014-10-19 13:29:00,Adoption,NaN,1,Spayed Female,8.571429,Domestic Shorthair Mix,Black,...,0,0,0,0,0,0,0,0,0,0
26707,A682690,NaN,2014-07-01 17:06:00,Euthanasia,Suffering,1,Unknown,1.000000,Domestic Shorthair Mix,Brown Tabby,...,0,0,0,0,0,0,0,0,0,0
26708,A666920,Herbie,2013-11-13 17:32:00,Transfer,Partner,0,Neutered Male,104.285714,Chihuahua Shorthair Mix,White/Brown,...,0,0,0,0,0,0,0,0,0,0
26709,A714386,NaN,2015-10-24 00:00:00,Adoption,NaN,0,Spayed Female,1.000000,Chihuahua Shorthair Mix,Rare,...,0,0,0,0,0,0,0,0,0,0
26710,A692622,Bonnie,2014-11-24 17:21:00,Transfer,Partner,0,Intact Female,1.000000,Chihuahua Shorthair/Yorkshire Terrier,Brown/Black,...,0,0,0,0,0,0,0,0,0,0
26711,A666284,Sonja,2013-10-30 18:32:00,Transfer,Partner,0,Intact Female,1.000000,Cocker Spaniel/Dachshund,Buff,...,0,0,0,0,0,0,0,0,0,0
26712,A535277,Merlin,2015-04-20 16:04:00,Return_to_owner,NaN,0,Neutered Male,625.714286,Rat Terrier,Chocolate/Tan,...,0,0,0,0,0,0,0,0,0,0
26713,A671169,NaN,2014-01-20 17:37:00,Euthanasia,Suffering,1,Intact Female,938.571429,Domestic Longhair Mix,Tortie,...,0,0,0,0,0,0,0,0,0,0
26714,A679031,Pete,2014-05-31 16:11:00,Adoption,NaN,1,Spayed Female,8.571429,Domestic Shorthair Mix,Orange Tabby,...,0,0,0,0,0,0,0,0,0,0
26715,A708833,Luna,2015-08-05 17:03:00,Adoption,NaN,0,Spayed Female,8.571429,Pointer Mix,Black/White,...,0,0,0,0,0,0,0,0,0,0
26716,A697158,Max,2015-05-02 21:04:00,Adoption,Offsite,0,Neutered Male,8.571429,Newfoundland Mix,White/Black,...,0,0,0,0,0,0,0,0,0,0
26717,A519949,Bella,2014-06-30 17:34:00,Return_to_owner,NaN,0,Spayed Female,469.285714,Bullmastiff Mix,Black,...,0,0,0,0,0,0,0,0,0,0
26718,A701044,NaN,2015-04-28 14:26:00,Adoption,NaN,0,Neutered Male,8.571429,Siberian Husky/German Shepherd,Black/Tricolor,...,0,0,0,0,0,0,0,0,0,0
26719,A707871,NaN,2015-07-20 09:00:00,Transfer,SCRP,1,Unknown,104.285714,Domestic Shorthair Mix,Brown Tabby/White,...,0,0,0,0,0,0,0,0,0,0
26720,A704405,Brownie,2015-07-18 14:08:00,Adoption,NaN,1,Spayed Female,8.571429,Domestic Shorthair Mix,Brown Tabby,...,0,0,0,0,0,0,0,0,0,0
26721,A662019,Green Bean,2014-07-17 09:43:00,Adoption,Foster,1,Spayed Female,260.714286,Domestic Shorthair Mix,Black,...,0,0,0,0,0,0,0,0,0,0
26722,A687056,NaN,2014-08-31 09:00:00,Transfer,SCRP,1,Intact Male,21.428571,Domestic Shorthair Mix,Orange Tabby,...,0,0,0,0,0,0,0,0,0,0
26723,A716997,Zeus,2016-01-29 18:52:00,Adoption,NaN,0,Neutered Male,312.857143,Staffordshire Mix,Blue/White,...,0,0,0,0,0,0,0,0,0,0
26724,A702446,NaN,2015-05-14 11:56:00,Transfer,Partner,1,Intact Male,1.000000,Domestic Shorthair Mix,Brown Tabby/White,...,0,0,0,0,0,0,0,0,0,0
26725,A718934,NaN,2016-01-20 18:59:00,Transfer,SCRP,1,Spayed Female,12.857143,Domestic Shorthair Mix,Brown Tabby,...,0,0,0,0,0,0,0,0,0,0
26726,A698128,Zeus,2015-03-09 13:33:00,Adoption,NaN,0,Neutered Male,208.571429,Old English Bulldog Mix,White/Tan,...,0,0,0,0,0,0,1,0,0,0
26727,A677478,NaN,2014-04-27 12:22:00,Transfer,Partner,1,Intact Male,4.000000,Domestic Shorthair Mix,Black,...,0,0,0,0,0,0,0,0,0,0
26728,A706629,NaN,2015-07-02 09:00:00,Transfer,SCRP,1,Intact Male,1.000000,Domestic Shorthair Mix,Brown Tabby/White,...,0,0,0,0,0,0,0,0,0,0

In [29]:
df.columns.values

array(['AnimalID', 'Name', 'DateTime', 'OutcomeType', 'OutcomeSubtype',
       'AnimalType', 'SexuponOutcome', 'AgeuponOutcome', 'Breed', 'Color',
       'Sterilization', 'Gender', 'Sterilization_Neutered',
       'Gender_Neutered', 'Gender_Unknown', 'Color_Black',
       'Color_Black Brindle', 'Color_Black Brindle/White',
       'Color_Black Smoke', 'Color_Black Tabby', 'Color_Black Tabby/White',
       'Color_Black/Brown', 'Color_Black/Brown Brindle',
       'Color_Black/Gray', 'Color_Black/Tan', 'Color_Black/Tricolor',
       'Color_Black/White', 'Color_Blue', 'Color_Blue Merle',
       'Color_Blue Merle/Tan', 'Color_Blue Merle/White',
       'Color_Blue Point', 'Color_Blue Tabby', 'Color_Blue Tabby/White',
       'Color_Blue Tick', 'Color_Blue/Tan', 'Color_Blue/White',
       'Color_Brown', 'Color_Brown Brindle', 'Color_Brown Brindle/White',
       'Color_Brown Merle', 'Color_Brown Merle/White', 'Color_Brown Tabby',
       'Color_Brown Tabby/White', 'Color_Brown/Black', 'Color_Brown/Tan',
       'Color_Brown/White', 'Color_Buff', 'Color_Buff/White',
       'Color_Calico', 'Color_Calico Point', 'Color_Calico/White',
       'Color_Chocolate', 'Color_Chocolate/Tan', 'Color_Chocolate/White',
       'Color_Cream', 'Color_Cream Tabby', 'Color_Cream Tabby/White',
       'Color_Cream/White', 'Color_Fawn', 'Color_Fawn/Black',
       'Color_Fawn/White', 'Color_Flame Point', 'Color_Gold',
       'Color_Gold/White', 'Color_Gray', 'Color_Gray Tabby',
       'Color_Gray/White', 'Color_Lilac Point', 'Color_Lynx Point',
       'Color_Orange Tabby', 'Color_Orange Tabby/White',
       'Color_Orange/White', 'Color_Rare', 'Color_Red', 'Color_Red Merle',
       'Color_Red Merle/White', 'Color_Red/Black', 'Color_Red/Tan',
       'Color_Red/White', 'Color_Sable', 'Color_Sable/White',
       'Color_Seal Point', 'Color_Seal Point/White', 'Color_Silver',
       'Color_Silver Tabby', 'Color_Silver/Tan', 'Color_Tan',
       'Color_Tan/Black', 'Color_Tan/Brown', 'Color_Tan/White',
       'Color_Torbie', 'Color_Torbie/White', 'Color_Tortie',
       'Color_Tortie Point', 'Color_Tortie/White', 'Color_Tricolor',
       'Color_Tricolor/White', 'Color_White', 'Color_White/Black',
       'Color_White/Blue', 'Color_White/Brown',
       'Color_White/Brown Brindle', 'Color_White/Brown Tabby',
       'Color_White/Buff', 'Color_White/Chocolate', 'Color_White/Cream',
       'Color_White/Gray', 'Color_White/Orange',
       'Color_White/Orange Tabby', 'Color_White/Red', 'Color_White/Tan',
       'Color_White/Tricolor', 'Color_Yellow', 'Color_Yellow/White'], dtype=object)

In [30]:
training_columns = ['AnimalType', 'AgeuponOutcome'] + \
    [x for x in df.columns if 'Color_' in x] + \
    [x for x in df.columns if 'Gender_' in x] + \
    [x for x in df.columns if 'Sterilization_' in x]

In [31]:
df['OutcomeType'].value_counts()

Adoption           10769
Transfer            9422
Return_to_owner     4786
Euthanasia          1555
Died                 197
Name: OutcomeType, dtype: int64

In [62]:
outcomes2numbers = {'Adoption': 0, 'Transfer': 1, 'Return_to_owner': 2, 'Euthanasia': 3, 'Died': 4}
df['OutcomeType'] = df['OutcomeType'].map(outcomes2numbers)

In [33]:
len(df_test[training_columns].columns)

105

In [34]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(random_state=42, n_estimators=100, oob_score=True)
clf.fit(df[training_columns], df['OutcomeType'])

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=100, n_jobs=1, oob_score=True, random_state=42,
            verbose=0, warm_start=False)

In [35]:
clf.oob_score_

0.6063077556212354

In [36]:
clf.predict(df_test[training_columns])

array([0, 0, 0, ..., 1, 0, 2])

In [59]:
proba = clf.predict_proba(df_test[training_columns]) + 0.0001

In [67]:
submission = pd.read_csv('sample_submission.csv')
for outcome in ['Adoption', 'Died', 'Euthanasia', 'Return_to_owner', 'Transfer']:
    submission[outcome] = proba[:, outcomes2numbers[outcome]]

submission.to_csv("sub.csv",index=False)

In [66]:
submission

          ID  Adoption      Died  Euthanasia  Return_to_owner  Transfer
0          1  0.763011  0.000100    0.000100         0.237189  0.000100
1          2  0.481305  0.000100    0.026119         0.308083  0.184892
2          3  0.612450  0.000100    0.010773         0.075467  0.301710
3          4  0.000100  0.000100    0.056481         0.012600  0.931219
4          5  0.468520  0.000100    0.023548         0.315318  0.193014
5          6  0.000100  0.000100    0.390354         0.133465  0.476481
6          7  0.043433  0.000100    0.120267         0.011767  0.824933
7          8  0.000100  0.000100    0.010790         0.028290  0.961219
8          9  0.690795  0.000100    0.000100         0.094524  0.214982
9         10  0.619771  0.000100    0.014147         0.182244  0.184238
10        11  0.020100  0.390100    0.050100         0.000100  0.540100
11        12  0.576692  0.000100    0.047360         0.259023  0.117325
12        13  0.352850  0.000100    0.000100         0.001529  0.645921
13        14  0.468520  0.000100    0.023548         0.315318  0.193014
14        15  0.627525  0.000100    0.000100         0.200811  0.171964
15        16  0.764880  0.000100    0.000100         0.235320  0.000100
16        17  0.000100  0.000100    0.009544         0.358465  0.632290
17        18  0.000100  0.001529    0.404957         0.481505  0.112410
18        19  0.000100  0.004708    0.009496         0.024582  0.961614
19        20  0.372229  0.000100    0.126049         0.100160  0.401962
20        21  0.000100  0.000100    0.120786         0.000100  0.879414
21        22  0.420450  0.000100    0.004100         0.067583  0.508267
22        23  0.535615  0.000100    0.028983         0.237442  0.198360
23        24  0.546055  0.000100    0.033797         0.093989  0.326559
24        25  0.583971  0.000100    0.008546         0.161639  0.246243
25        26  0.035706  0.048432    0.138325         0.005761  0.772275
26        27  0.940805  0.000100    0.000100         0.000100  0.059395
27        28  0.878807  0.000100    0.000100         0.046262  0.075231
28        29  0.365011  0.006947    0.058358         0.398058  0.172127
29        30  0.413900  0.000100    0.039068         0.317398  0.230033
...      ...       ...       ...         ...              ...       ...
11426  11427  0.000100  0.000100    0.016600         0.867647  0.116053
11427  11428  0.005100  0.012195    0.017112         0.010100  0.955993
11428  11429  0.329138  0.000100    0.081941         0.365047  0.224274
11429  11430  0.343817  0.000100    0.000100         0.400029  0.256453
11430  11431  0.467755  0.067177    0.000100         0.000100  0.465368
11431  11432  0.329803  0.000100    0.000100         0.000100  0.670397
11432  11433  0.464927  0.000100    0.023181         0.276418  0.235874
11433  11434  0.229525  0.022714    0.057406         0.000100  0.690754
11434  11435  0.521928  0.000100    0.059072         0.137556  0.281844
11435  11436  0.540328  0.000100    0.009514         0.066042  0.384516
11436  11437  0.608130  0.000100    0.000100         0.073026  0.319143
11437  11438  0.641840  0.000100    0.000100         0.014814  0.343646
11438  11439  0.000100  0.000100    0.000100         0.168782  0.831418
11439  11440  0.000100  0.000100    0.280266         0.297647  0.422387
11440  11441  0.612450  0.000100    0.010773         0.075467  0.301710
11441  11442  0.000100  0.000100    0.446012         0.470477  0.083811
11442  11443  0.000100  0.006591    0.577777         0.097689  0.318343
11443  11444  0.763329  0.000100    0.000100         0.000100  0.236871
11444  11445  0.256650  0.000100    0.026366         0.205163  0.512221
11445  11446  0.548509  0.000100    0.006916         0.000100  0.444875
11446  11447  0.894396  0.000100    0.003738         0.008554  0.093713
11447  11448  0.569571  0.000100    0.027072         0.214920  0.188838
11448  11449  0.878807  0.000100    0.000100         0.046262  0.075231
11449  11450  0.825503  0.000100    0.000100         0.036175  0.138621
11450  11451  0.749698  0.000100    0.000100         0.000100  0.250502
11451  11452  0.894396  0.000100    0.003738         0.008554  0.093713
11452  11453  0.000100  0.049505    0.000100         0.000100  0.950695
11453  11454  0.476658  0.000100    0.000100         0.045119  0.478524
11454  11455  0.521928  0.000100    0.059072         0.137556  0.281844
11455  11456  0.328616  0.000100    0.000100         0.373971  0.297713

[11456 rows x 6 columns]

# Cross validation

In [ ]:
from sklearn.model_selection import StratifiedKFold, cross_val_score

for n_splits in xrange(2, 11):
    n_splits_score_means = []
    n_splits_score_std = []
    for i in xrange(7):
        kfold = StratifiedKFold(n_splits=n_splits, random_state=i, shuffle=True)
        clf = RandomForestClassifier(random_state=42, n_estimators=100)
        cv_score = cross_val_score(RandomForestClassifier(random_state=42, n_estimators=100),
                                   df_test[training_columns], df['OutcomeType'], cv=kfold)

        print 'n_splits={}, i={}, mean={}, std={}, score={}'.format(
            n_splits, i, mean(cv_score), std(cv_score), cv_score)
        
        n_splits_score_means[n_splits] += mean(cv_score) / 7
        n_splits_score_std[n_splits] += mean(cv_score) / 7
        


    # >>> for train_index, test_index in skf.split(X, y):
    # ...    print("TRAIN:", train_index, "TEST:", test_index)
    # ...    X_train, X_test = X[train_index], X[test_index]
    # ...    y_train, y_test = y[train_index], y[test_index]
    # TRAIN: [1 3] TEST: [0 2]
    # TRAIN: [0 2] TEST: [1 3]

## Задание:
1) постройте кривую oob_score относительно количества деревьев в лесе и выберете оптимальное значение n_estimators

2) добавьте признаки о породе животных, улучшает ли это качество предсказания? В качестве домашнего задания, попробуйте разобраться с обработкой пород из https://www.kaggle.com/andraszsom/shelter-animal-outcomes/dog-breeds-dog-groups

3) разбейте df на train и test с помощью train_test_split. Посчитайте score (метод класса RandomForestClassifier) для train и test. Есть ли у вас переобучение?

4) попробуйте использовать kNN. Помогают ли признаки цвета или приводят к проклятию размерности? Сколько признаков цвета является оптимальным?

5) супер-задание: загрузите датасет https://www.kaggle.com/deepmatrix/imdb-5000-movie-dataset , попробуйте предсказать рейтинг фильма. Если бы вы создавали сервис, который предсказывает рейтинг премьеры, какую бы вы метрику выбрали для оценки своего алгоритма?

<img src="http://static.diary.ru/userdir/2/3/5/3/2353834/66835239.jpg" width=300>